fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   FOSUserBundle:Resetting:email.txt.twig
    from_email:
        address: "contact@masommeliere.fr"
        sender_name: "contact@masommeliere.fr"
