security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
         
        login:
            host: api\.masommeliere\.fr
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            host: api\.masommeliere\.fr
            pattern: ^/
            stateless: true
            anonymous: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            host: admin\.masommeliere\.fr
            access_denied_handler: App\Security\AccessDeniedHandler
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.masommeliere\.fr }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.masommeliere\.fr }
        - { path: ^/redirectionTo, role: IS_AUTHENTICATED_FULLY, host: admin\.masommeliere\.fr }
        - { path: ^/admin, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/actualite, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/categorie, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/cible, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/contactuser, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/image, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/module, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/pdf, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/pressbook, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/prestation, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/prix, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/targetprice, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
        - { path: ^/contact, role: ROLE_ADMIN, host: admin\.masommeliere\.fr }
