to_ng:
    path: /
    host: 'masommeliere.fr'
    defaults:
        url: 'http://masommeliere.fr'

controllers:
    host: 'admin.masommeliere.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.masommeliere.fr'
    path: /login_check
    methods: [POST]

api_controllers:
    host: 'api.masommeliere.fr'
    resource: ../../src/ApiController/
    type: annotation
